item = ('cat',-6,(1,2))
print(item)
print(type(item))
print(item[0],item[1],item[2])
item = ('cat')
print(item)
print(type(item))
print(item[0])
print(type(item[0]))
item = ()
print(item)
print(type(item))